# Generated by Django 5.0.7 on 2024-09-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allcontact",
            name="avatar",
            field=models.ImageField(
                default="media/avatar-5261900_1920_1.png ", upload_to="media/"
            ),
        ),
    ]
