# Generated by Django 5.0.7 on 2024-09-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0002_allcontact_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="allcontact",
            name="avatar_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="allcontact",
            name="avatar",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="avatars/"
            ),
        ),
    ]
