# Generated by Django 5.0.7 on 2024-10-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0003_allcontact_avatar_public_id_alter_allcontact_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allcontact",
            name="avatar_public_id",
        ),
        migrations.AddField(
            model_name="allcontact",
            name="avatar_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="allcontact",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
