# Generated by Django 5.0.7 on 2026-01-28 02:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0004_remove_allcontact_avatar_public_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allcontact",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("N", "Neutral")],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="allcontact",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
