# Generated by Django 5.0.7 on 2024-08-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0004_alter_profile_address_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_birth",
            field=models.DateField(default="2001-01-01"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(default="my address"),
        ),
    ]
