# Generated by Django 5.0.7 on 2024-09-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0005_profile_date_birth_alter_profile_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="core/media/avatar-5261896_1920_2.png",
                upload_to="profile_images",
            ),
        ),
    ]
