# Generated by Django 5.0.7 on 2024-09-05 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="expire_at",
        ),
        migrations.AddField(
            model_name="note",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
