# Generated by Django 5.0.7 on 2026-01-29 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_notelist_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="status",
        ),
        migrations.RemoveField(
            model_name="note",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="note",
            name="expire_at",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="notebook",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notes.notelist",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(blank=True, to="notes.tag"),
        ),
        migrations.AlterField(
            model_name="notelist",
            name="list_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="notelist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notebooks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
